feat: adds responsible role to fedramp transform
oscal-compass/compliance-trestle-fedramp pull request #39
Opened 2024-04-25 19:19 UTC by jpower432

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [X] All commits are signed-off.

## Summary

Slacked with #34 

Adds population of responsible role to `fedramp-transform`

Closes #20 (final PR to handle all of the complete criteria)

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle-fedramp)

2024-07-24 19:09 UTC, gvauter requested changes
One suggestion on not instantiating a class instance just to avoid potential unwanted init behavior down the road.

2024-07-26 20:07 UTC, jpower432 commented on trestle_fedramp/core/ssp_reader.py
> +            label = self._control_labels_by_id.get(control_id, '')
Good catch. This should be `None` and the label would be absent in this case.

2024-07-29 15:59 UTC, gvauter approved these changes
LGTM

2024-08-27 10:53 UTC, vikas-agarwal76 approved these changes
LGTM

2024-09-19 16:19 UTC, jpower432 commented
Merging this now that 0.3.0 has been released.

2024-09-19 16:24 UTC, merged